const countries = {
    "Afghanistan": { code: "AF", dialCode: "+93", name: "Afghanistan" },
    "Åland Islands": { code: "AX", dialCode: "+358", name: "Åland Islands" },
    "Albania": { code: "AL", dialCode: "+355", name: "Albania" },
    "Algeria": { code: "DZ", dialCode: "+213", name: "Algeria" },
    "American Samoa": { code: "AS", dialCode: "+1-684", name: "American Samoa" },
    "Andorra": { code: "AD", dialCode: "+376", name: "Andorra" },
    "Angola": { code: "AO", dialCode: "+244", name: "Angola" },
    "Anguilla": { code: "AI", dialCode: "+1-264", name: "Anguilla" },
    "Antarctica": { code: "AQ", dialCode: "+672", name: "Antarctica" },
    "Antigua and Barbuda": { code: "AG", dialCode: "+1-268", name: "Antigua and Barbuda" },
    "Argentina": { code: "AR", dialCode: "+54", name: "Argentina" },
    "Armenia": { code: "AM", dialCode: "+374", name: "Armenia" },
    "Aruba": { code: "AW", dialCode: "+297", name: "Aruba" },
    "Australia": { code: "AU", dialCode: "+61", name: "Australia" },
    "Austria": { code: "AT", dialCode: "+43", name: "Austria" },
    "Azerbaijan": { code: "AZ", dialCode: "+994", name: "Azerbaijan" },
    "Bahamas": { code: "BS", dialCode: "+1-242", name: "Bahamas" },
    "Bahrain": { code: "BH", dialCode: "+973", name: "Bahrain" },
    "Bangladesh": { code: "BD", dialCode: "+880", name: "Bangladesh" },
    "Barbados": { code: "BB", dialCode: "+1-246", name: "Barbados" },
    "Belarus": { code: "BY", dialCode: "+375", name: "Belarus" },
    "Belgium": { code: "BE", dialCode: "+32", name: "Belgium" },
    "Belize": { code: "BZ", dialCode: "+501", name: "Belize" },
    "Benin": { code: "BJ", dialCode: "+229", name: "Benin" },
    "Bermuda": { code: "BM", dialCode: "+1-441", name: "Bermuda" },
    "Bhutan": { code: "BT", dialCode: "+975", name: "Bhutan" },
    "Bolivia": { code: "BO", dialCode: "+591", name: "Bolivia" },
    "Bosnia and Herzegovina": { code: "BA", dialCode: "+387", name: "Bosnia and Herzegovina" },
    "Botswana": { code: "BW", dialCode: "+267", name: "Botswana" },
    "Bouvet Island": { code: "BV", dialCode: "", name: "Bouvet Island" },
    "Brazil": { code: "BR", dialCode: "+55", name: "Brazil" },
    "British Indian Ocean Territory": { code: "IO", dialCode: "+246", name: "British Indian Ocean Territory" },
    "Brunei Darussalam": { code: "BN", dialCode: "+673", name: "Brunei Darussalam" },
    "Bulgaria": { code: "BG", dialCode: "+359", name: "Bulgaria" },
    "Burkina Faso": { code: "BF", dialCode: "+226", name: "Burkina Faso" },
    "Burundi": { code: "BI", dialCode: "+257", name: "Burundi" },
    "Cambodia": { code: "KH", dialCode: "+855", name: "Cambodia" },
    "Cameroon": { code: "CM", dialCode: "+237", name: "Cameroon" },
    "Canada": { code: "CA", dialCode: "+1", name: "Canada" },
    "Cape Verde": { code: "CV", dialCode: "+238", name: "Cape Verde" },
    "Cayman Islands": { code: "KY", dialCode: "+1-345", name: "Cayman Islands" },
    "Central African Republic": { code: "CF", dialCode: "+236", name: "Central African Republic" },
    "Chad": { code: "TD", dialCode: "+235", name: "Chad" },
    "Chile": { code: "CL", dialCode: "+56", name: "Chile" },
    "China": { code: "CN", dialCode: "+86", name: "China" },
    "Christmas Island": { code: "CX", dialCode: "+61", name: "Christmas Island" },
    "Cocos (Keeling) Islands": { code: "CC", dialCode: "+61", name: "Cocos (Keeling) Islands" },
    "Colombia": { code: "CO", dialCode: "+57", name: "Colombia" },
    "Comoros": { code: "KM", dialCode: "+269", name: "Comoros" },
    "Congo": { code: "CG", dialCode: "+242", name: "Congo" },
    "Congo, The Democratic Republic of the": { code: "CD", dialCode: "+243", name: "Congo, The Democratic Republic of the" },
    "Cook Islands": { code: "CK", dialCode: "+682", name: "Cook Islands" },
    "Costa Rica": { code: "CR", dialCode: "+506", name: "Costa Rica" },
    "Cote D'Ivoire": { code: "CI", dialCode: "+225", name: "Cote D'Ivoire" },
    "Croatia": { code: "HR", dialCode: "+385", name: "Croatia" },
    "Cuba": { code: "CU", dialCode: "+53", name: "Cuba" },
    "Cyprus": { code: "CY", dialCode: "+357", name: "Cyprus" },
    "Czech Republic": { code: "CZ", dialCode: "+420", name: "Czech Republic" },
    "Denmark": { code: "DK", dialCode: "+45", name: "Denmark" },
    "Djibouti": { code: "DJ", dialCode: "+253", name: "Djibouti" },
    "Dominica": { code: "DM", dialCode: "+1-767", name: "Dominica" },
    "Dominican Republic": { code: "DO", dialCode: "+1-809", name: "Dominican Republic" },
    "Ecuador": { code: "EC", dialCode: "+593", name: "Ecuador" },
    "Egypt": { code: "EG", dialCode: "+20", name: "Egypt" },
    "El Salvador": { code: "SV", dialCode: "+503", name: "El Salvador" },
    "Equatorial Guinea": { code: "GQ", dialCode: "+240", name: "Equatorial Guinea" },
    "Eritrea": { code: "ER", dialCode: "+291", name: "Eritrea" },
    "Estonia": { code: "EE", dialCode: "+372", name: "Estonia" },
    "Ethiopia": { code: "ET", dialCode: "+251", name: "Ethiopia" },
    "Falkland Islands (Malvinas)": { code: "FK", dialCode: "+500", name: "Falkland Islands (Malvinas)" },
    "Faroe Islands": { code: "FO", dialCode: "+298", name: "Faroe Islands" },
    "Fiji": { code: "FJ", dialCode: "+679", name: "Fiji" },
    "Finland": { code: "FI", dialCode: "+358", name: "Finland" },
    "France": { code: "FR", dialCode: "+33", name: "France" },
    "French Guiana": { code: "GF", dialCode: "+594", name: "French Guiana" },
    "French Polynesia": { code: "PF", dialCode: "+689", name: "French Polynesia" },
    "French Southern Territories": { code: "TF", dialCode: "", name: "French Southern Territories" },
    "Gabon": { code: "GA", dialCode: "+241", name: "Gabon" },
    "Gambia": { code: "GM", dialCode: "+220", name: "Gambia" },
    "Georgia": { code: "GE", dialCode: "+995", name: "Georgia" },
    "Germany": { code: "DE", dialCode: "+49", name: "Germany" },
    "Ghana": { code: "GH", dialCode: "+233", name: "Ghana" },
    "Gibraltar": { code: "GI", dialCode: "+350", name: "Gibraltar" },
    "Greece": { code: "GR", dialCode: "+30", name: "Greece" },
    "Greenland": { code: "GL", dialCode: "+299", name: "Greenland" },
    "Grenada": { code: "GD", dialCode: "+1-473", name: "Grenada" },
    "Guadeloupe": { code: "GP", dialCode: "+590", name: "Guadeloupe" },
    "Guam": { code: "GU", dialCode: "+1-671", name: "Guam" },
    "Guatemala": { code: "GT", dialCode: "+502", name: "Guatemala" },
    "Guernsey": { code: "GG", dialCode: "+44-1481", name: "Guernsey" },
    "Guinea": { code: "GN", dialCode: "+224", name: "Guinea" },
    "Guinea-Bissau": { code: "GW", dialCode: "+245", name: "Guinea-Bissau" },
    "Guyana": { code: "GY", dialCode: "+592", name: "Guyana" },
    "Haiti": { code: "HT", dialCode: "+509", name: "Haiti" },
    "Heard Island and Mcdonald Islands": { code: "HM", dialCode: "", name: "Heard Island and Mcdonald Islands" },
    "Holy See (Vatican City State)": { code: "VA", dialCode: "+379", name: "Holy See (Vatican City State)" },
    "Honduras": { code: "HN", dialCode: "+504", name: "Honduras" },
    "Hong Kong": { code: "HK", dialCode: "+852", name: "Hong Kong" },
    "Hungary": { code: "HU", dialCode: "+36", name: "Hungary" },
    "Iceland": { code: "IS", dialCode: "+354", name: "Iceland" },
    "India": { code: "IN", dialCode: "+91", name: "India" },
    "Indonesia": { code: "ID", dialCode: "+62", name: "Indonesia" },
    "Iran, Islamic Republic Of": { code: "IR", dialCode: "+98", name: "Iran, Islamic Republic Of" },
    "Iraq": { code: "IQ", dialCode: "+964", name: "Iraq" },
    "Ireland": { code: "IE", dialCode: "+353", name: "Ireland" },
    "Isle of Man": { code: "IM", dialCode: "+44-1624", name: "Isle of Man" },
    "Israel": { code: "IL", dialCode: "+972", name: "Israel" },
    "Italy": { code: "IT", dialCode: "+39", name: "Italy" },
    "Jamaica": { code: "JM", dialCode: "+1-876", name: "Jamaica" },
    "Japan": { code: "JP", dialCode: "+81", name: "Japan" },
    "Jersey": { code: "JE", dialCode: "+44-1534", name: "Jersey" },
    "Jordan": { code: "JO", dialCode: "+962", name: "Jordan" },
    "Kazakhstan": { code: "KZ", dialCode: "+7", name: "Kazakhstan" },
    "Kenya": { code: "KE", dialCode: "+254", name: "Kenya" },
    "Kiribati": { code: "KI", dialCode: "+686", name: "Kiribati" },
    "Korea, Democratic People's Republic of": { code: "KP", dialCode: "+850", name: "Korea, Democratic People's Republic of" },
    "Korea, Republic of": { code: "KR", dialCode: "+82", name: "Korea, Republic of" },
    "Kuwait": { code: "KW", dialCode: "+965", name: "Kuwait" },
    "Kyrgyzstan": { code: "KG", dialCode: "+996", name: "Kyrgyzstan"},
    "Lao People's Democratic Republic": { code: "LA", dialCode: "+856", name: "Lao People's Democratic Republic" },
    "Latvia": { code: "LV", dialCode: "+371", name: "Latvia" },
    "Lebanon": { code: "LB", dialCode: "+961", name: "Lebanon" },
    "Lesotho": { code: "LS", dialCode: "+266", name: "Lesotho" },
    "Liberia": { code: "LR", dialCode: "+231", name: "Liberia" },
    "Libyan Arab Jamahiriya": { code: "LY", dialCode: "+218", name: "Libyan Arab Jamahiriya" },
    "Liechtenstein": { code: "LI", dialCode: "+423", name: "Liechtenstein" },
    "Lithuania": { code: "LT", dialCode: "+370", name: "Lithuania" },
    "Luxembourg": { code: "LU", dialCode: "+352", name: "Luxembourg" },
    "Macao": { code: "MO", dialCode: "+853", name: "Macao" },
    "Macedonia, The Former Yugoslav Republic of": { code: "MK", dialCode: "+389", name: "Macedonia, The Former Yugoslav Republic of" },
    "Madagascar": { code: "MG", dialCode: "+261", name: "Madagascar" },
    "Malawi": { code: "MW", dialCode: "+265", name: "Malawi" },
    "Malaysia": { code: "MY", dialCode: "+60", name: "Malaysia" },
    "Maldives": { code: "MV", dialCode: "+960", name: "Maldives" },
    "Mali": { code: "ML", dialCode: "+223", name: "Mali" },
    "Malta": { code: "MT", dialCode: "+356", name: "Malta" },
    "Marshall Islands": { code: "MH", dialCode: "+692", name: "Marshall Islands" },
    "Martinique": { code: "MQ", dialCode: "+596", name: "Martinique" },
    "Mauritania": { code: "MR", dialCode: "+222", name: "Mauritania" },
    "Mauritius": { code: "MU", dialCode: "+230", name: "Mauritius" },
    "Mayotte": { code: "YT", dialCode: "+262", name: "Mayotte" },
    "Mexico": { code: "MX", dialCode: "+52", name: "Mexico" },
    "Micronesia, Federated States of": { code: "FM", dialCode: "+691", name: "Micronesia, Federated States of" },
    "Moldova, Republic of": { code: "MD", dialCode: "+373", name: "Moldova, Republic of" },
    "Monaco": { code: "MC", dialCode: "+377", name: "Monaco" },
    "Mongolia": { code: "MN", dialCode: "+976", name: "Mongolia" },
    "Montserrat": { code: "MS", dialCode: "+1-664", name: "Montserrat" },
    "Morocco": { code: "MA", dialCode: "+212", name: "Morocco" },
    "Mozambique": { code: "MZ", dialCode: "+258", name: "Mozambique" },
    "Myanmar": { code: "MM", dialCode: "+95", name: "Myanmar" },
    "Namibia": { code: "NA", dialCode: "+264", name: "Namibia" },
    "Nauru": { code: "NR", dialCode: "+674", name: "Nauru" },
    "Nepal": { code: "NP", dialCode: "+977", name: "Nepal" },
    "Netherlands": { code: "NL", dialCode: "+31", name: "Netherlands" },
    "Netherlands Antilles": { code: "AN", dialCode: "+599", name: "Netherlands Antilles" },
    "New Caledonia": { code: "NC", dialCode: "+687", name: "New Caledonia" },
    "New Zealand": { code: "NZ", dialCode: "+64", name: "New Zealand" },
    "Nicaragua": { code: "NI", dialCode: "+505", name: "Nicaragua" },
    "Niger": { code: "NE", dialCode: "+227", name: "Niger" },
    "Nigeria": { code: "NG", dialCode: "+234", name: "Nigeria" },
    "Niue": { code: "NU", dialCode: "+683", name: "Niue" },
    "Norfolk Island": { code: "NF", dialCode: "+672", name: "Norfolk Island" },
    "Northern Mariana Islands": { code: "MP", dialCode: "+1-670", name: "Northern Mariana Islands" },
    "Norway": { code: "NO", dialCode: "+47", name: "Norway" },
    "Oman": { code: "OM", dialCode: "+968", name: "Oman" },
    "Pakistan": { code: "PK", dialCode: "+92", name: "Pakistan" },
    "Palau": { code: "PW", dialCode: "+680", name: "Palau" },
    "Palestinian Territory, Occupied": { code: "PS", dialCode: "+970", name: "Palestinian Territory, Occupied" },
    "Panama": { code: "PA", dialCode: "+507", name: "Panama" },
    "Papua New Guinea": { code: "PG", dialCode: "+675", name: "Papua New Guinea" },
    "Paraguay": { code: "PY", dialCode: "+595", name: "Paraguay" },
    "Peru": { code: "PE", dialCode: "+51", name: "Peru" },
    "Philippines": { code: "PH", dialCode: "+63", name: "Philippines" },
    "Pitcairn": { code: "PN", dialCode: "+872", name: "Pitcairn" },
    "Poland": { code: "PL", dialCode: "+48", name: "Poland" },
    "Portugal": { code: "PT", dialCode: "+351", name: "Portugal" },
    "Puerto Rico": { code: "PR", dialCode: "+1-787", name: "Puerto Rico" },
    "Qatar": { code: "QA", dialCode: "+974", name: "Qatar" },
    "Reunion": { code: "RE", dialCode: "+262", name: "Reunion" },
    "Romania": { code: "RO", dialCode: "+40", name: "Romania" },
    "Russian Federation": { code: "RU", dialCode: "+7", name: "Russian Federation" },
    "RWANDA": { code: "RW", dialCode: "+250", name: "RWANDA" },
    "Saint Helena": { code: "SH", dialCode: "+290", name: "Saint Helena" },
    "Saint Kitts and Nevis": { code: "KN", dialCode: "+1-869", name: "Saint Kitts and Nevis" },
    "Saint Lucia": { code: "LC", dialCode: "+1-758", name: "Saint Lucia" },
    "Saint Pierre and Miquelon": { code: "PM", dialCode: "+508", name: "Saint Pierre and Miquelon" },
    "Saint Vincent and the Grenadines": { code: "VC", dialCode: "+1-784", name: "Saint Vincent and the Grenadines" },
    "Samoa": { code: "WS", dialCode: "+685", name: "Samoa" },
    "San Marino": { code: "SM", dialCode: "+378", name: "San Marino" },
    "Sao Tome and Principe": { code: "ST", dialCode: "+239", name: "Sao Tome and Principe" },
    "Saudi Arabia": { code: "SA", dialCode: "+966", name: "Saudi Arabia" },
    "Senegal": { code: "SN", dialCode: "+221", name: "Senegal" },
    "Serbia and Montenegro": { code: "CS", dialCode: "+381", name: "Serbia and Montenegro" },
    "Seychelles": { code: "SC", dialCode: "+248", name: "Seychelles" },
    "Sierra Leone": { code: "SL", dialCode: "+232", name: "Sierra Leone" },
    "Singapore": { code: "SG", dialCode: "+65", name: "Singapore" },
    "Slovakia": { code: "SK", dialCode: "+421", name: "Slovakia" },
    "Slovenia": { code: "SI", dialCode: "+386", name: "Slovenia" },
    "Solomon Islands": { code: "SB", dialCode: "+677", name: "Solomon Islands" },
    "Somalia": { code: "SO", dialCode: "+252", name: "Somalia" },
    "South Africa": { code: "ZA", dialCode: "+27", name: "South Africa" },
    "South Georgia and the South Sandwich Islands": { code: "GS", dialCode: "", name: "South Georgia and the South Sandwich Islands" },
    "Spain": { code: "ES", dialCode: "+34", name: "Spain" },
    "Sri Lanka": { code: "LK", dialCode: "+94", name: "Sri Lanka" },
    "Sudan": { code: "SD", dialCode: "+249", name: "Sudan" },
    "Suriname": { code: "SR", dialCode: "+597", name: "Suriname" },
    "Svalbard and Jan Mayen": { code: "SJ", dialCode: "+47", name: "Svalbard and Jan Mayen" },
    "Swaziland": { code: "SZ", dialCode: "+268", name: "Swaziland" },
    "Sweden": { code: "SE", dialCode: "+46", name: "Sweden" },
    "Switzerland": { code: "CH", dialCode: "+41", name: "Switzerland" },
    "Syrian Arab Republic": { code: "SY", dialCode: "+963", name: "Syrian Arab Republic" },
    "Taiwan, Province of China": { code: "TW", dialCode: "+886", name: "Taiwan, Province of China" },
    "Tajikistan": { code: "TJ", dialCode: "+992", name: "Tajikistan" },
    "Tanzania, United Republic of": { code: "TZ", dialCode: "+255", name: "Tanzania, United Republic of" },
    "Thailand": { code: "TH", dialCode: "+66", name: "Thailand" },
    "Timor-Leste": { code: "TL", dialCode: "+670", name: "Timor-Leste" },
    "Togo": { code: "TG", dialCode: "+228", name: "Togo" },
    "Tokelau": { code: "TK", dialCode: "+690", name: "Tokelau" },
    "Tonga": { code: "TO", dialCode: "+676", name: "Tonga" },
    "Trinidad and Tobago": { code: "TT", dialCode: "+1-868", name: "Trinidad and Tobago" },
    "Tunisia": { code: "TN", dialCode: "+216", name: "Tunisia" },
    "Turkey": { code: "TR", dialCode: "+90", name: "Turkey" },
    "Turkmenistan": { code: "TM", dialCode: "+993", name: "Turkmenistan" },
    "Turks and Caicos Islands": { code: "TC", dialCode: "+1-649", name: "Turks and Caicos Islands" },
    "Tuvalu": { code: "TV", dialCode: "+688", name: "Tuvalu" },
    "Uganda": { code: "UG", dialCode: "+256", name: "Uganda" },
    "Ukraine": { code: "UA", dialCode: "+380", name: "Ukraine" },
    "United Arab Emirates": { code: "AE", dialCode: "+971", name: "United Arab Emirates" },
    "United Kingdom": { code: "GB", dialCode: "+44", name: "United Kingdom" },
    "United States": { code: "US", dialCode: "+1", name: "United States" },
    "Uruguay": { code: "UY", dialCode: "+598", name: "Uruguay" },
    "Uzbekistan": { code: "UZ", dialCode: "+998", name: "Uzbekistan" },
    "Vanuatu": { code: "VU", dialCode: "+678", name: "Vanuatu" },
    "Venezuela": { code: "VE", dialCode: "+58", name: "Venezuela" },
    "Viet Nam": { code: "VN", dialCode: "+84", name: "Viet Nam" },
    "Virgin Islands, British": { code: "VG", dialCode: "+1-284", name: "Virgin Islands, British" },
    "Virgin Islands, U.S.": { code: "VI", dialCode: "+1-340", name: "Virgin Islands, U.S." },
    "Wallis and Futuna": { code: "WF", dialCode: "+681", name: "Wallis and Futuna" },
    "Western Sahara": { code: "EH", dialCode: "+212", name: "Western Sahara" },
    "Yemen": { code: "YE", dialCode: "+967", name: "Yemen" },
    "Zambia": { code: "ZM", dialCode: "+260", name: "Zambia" },
    "Zimbabwe": { code: "ZW", dialCode: "+263", name: "Zimbabwe" },
};

module.exports = countries;
